# Generated by Django 5.0.2 on 2024-03-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_attendance_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
